### ISSUE TITLE
不懂点

### ISSUE THREAD

**Issue by it985** [gaoxiaoduan/YoutubeToBilibiliHelp#1]
根据README中
{
  // 支持的平台
  "supported_target_platform": [
    "BZ"
  ],
  "uploads": [
    // 要监听的频道
    {
      "user": "xxx", // 监听频道的用户名
      "user_url": "https://www.youtube.com/@xxx/videos", // 监听用户的地址
      "publish_prefix": "", // 视频上传前缀
      "videos": [
      // 已经获取到的视频信息
      // 一下内容不需要配置
        {
          "id": "xxx", // 视频id
          "title": "xxx", // 视频原名称
          "video_url": "xxx", // 视频url
          "uploader": "xxx", // 视频上传者
          "upload_date": "xxx", // 上传时间
          "published": ["BZ"] // 已经发布的平台
        }
      ]
    }
  ]
}
是不是只需要配置以下
{
  // 支持的平台
  "supported_target_platform": [
    "BZ"
  ],
  "uploads": [
    // 要监听的频道
    {
      "user": "xxx", // 监听频道的用户名
      "user_url": "https://www.youtube.com/@xxx/videos", // 监听用户的地址
      "publish_prefix": "", // 视频上传前缀
    }
  ]
}
就ok了

**Comment by it985** [comment]
2运行(已科学)
![image](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/assets/62421120/75b0bfde-fef1-4b0f-9f78-59cd1b0f0293)

**Comment by gaoxiaoduan** [comment]
@it985 晚点写一个详细的教程文档

**Comment by gaoxiaoduan** [comment]
@it985 文档已出，可以查看最新文档解决此问题

**Comment by it985** [comment]
谢谢
