### ISSUE TITLE
您好，麻烦请教一下代理问题，您如果有空的话，还请劳烦帮忙解答一下，感谢

### ISSUE THREAD

**Issue by LeiWangJava** [gaoxiaoduan/YoutubeToBilibiliHelp#11]
![image](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/assets/52349591/9d203464-97f5-490f-976d-87e0eb581426)
![image](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/assets/52349591/bad45c5c-86fb-4e77-8c53-4da697923c8b)
![image](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/assets/52349591/a29a0752-0f3f-41cd-bd26-14c525aa8328)
![image](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/assets/52349591/4b561024-58c2-45be-a62b-8e1054cca924)
您好，请教一下关于代理的问题，如果我设置了代理为图中的地址，但是一直日志是耐心等待··时间长了就异常了
而我把配置改为直链，而win代理还是开着的时候，情况依旧如此
win系统开的
劳烦大佬有空帮忙解答一下
非常感谢了

**Comment by gaoxiaoduan** [comment]
@LeiWangJava 是因为`@user-1t6nh3zi81`这个用户在油管找不到。所以等不到
