### ISSUE TITLE
创建docker报错，日志如下

### ISSUE THREAD

**Issue by fengyuanluo** [gaoxiaoduan/YoutubeToBilibiliHelp#13]
=> ERROR [ 2/14] RUN apt-get update  && apt-get install -y chromium     fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf lib  7.6s
------                                                                                                                                                                  
 > [ 2/14] RUN apt-get update  && apt-get install -y chromium     fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1     --no-install-recommends:                                                                                                                                                     
0.446 Ign:1 http://deb.debian.org/debian bookworm InRelease                                                                                                             
0.447 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease                                                                                                     
0.447 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease                                                                                           
1.447 Ign:1 http://deb.debian.org/debian bookworm InRelease
1.448 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
1.448 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
3.448 Ign:1 http://deb.debian.org/debian bookworm InRelease
3.448 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
3.449 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
7.449 Err:1 http://deb.debian.org/debian bookworm InRelease
7.449   Temporary failure resolving 'deb.debian.org'
7.450 Err:2 http://deb.debian.org/debian bookworm-updates InRelease
7.450   Temporary failure resolving 'deb.debian.org'
7.450 Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
7.450   Temporary failure resolving 'deb.debian.org'
7.454 Reading package lists...
7.470 W: Failed to fetch http://deb.debian.org/debian/dists/bookworm/InRelease  Temporary failure resolving 'deb.debian.org'
7.470 W: Failed to fetch http://deb.debian.org/debian/dists/bookworm-updates/InRelease  Temporary failure resolving 'deb.debian.org'
7.470 W: Failed to fetch http://deb.debian.org/debian-security/dists/bookworm-security/InRelease  Temporary failure resolving 'deb.debian.org'
7.470 W: Some index files failed to download. They have been ignored, or old ones used instead.
7.479 Reading package lists...
7.489 Building dependency tree...
7.490 Reading state information...
7.491 Package fonts-freefont-ttf is not available, but is referred to by another package.
7.491 This may mean that the package is missing, has been obsoleted, or
7.491 is only available from another source
7.491 
7.491 E: Unable to locate package chromium
7.491 E: Unable to locate package fonts-ipafont-gothic
7.491 E: Unable to locate package fonts-wqy-zenhei
7.491 E: Unable to locate package fonts-thai-tlwg
7.491 E: Unable to locate package fonts-kacst
7.491 E: Package 'fonts-freefont-ttf' has no installation candidate
7.491 E: Unable to locate package libxss1
------
Dockerfile:4
--------------------
   3 |     # 安装 chromium 及字体
   4 | >>> RUN apt-get update \
   5 | >>>  && apt-get install -y chromium \
   6 | >>>     fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
   7 | >>>     --no-install-recommends
   8 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update  && apt-get install -y chromium     fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1     --no-install-recommends" did not complete successfully: exit code: 100

谢谢！

**Comment by fengyuanluo** [comment]
本地部署报错

failed to fetch global config RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (D:\AI\视频\YoutubeToBilibiliHelp\node_modules\.pnpm\got@11.8.6\node_modules\got\dist\source\core\index.js:970:111)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:526:35)
    at origin.emit (D:\AI\视频\YoutubeToBilibiliHelp\node_modules\.pnpm\@szmarczak+http-timer@4.0.6\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  code: 'ECONNRESET',
  timings: {
    start: 1709441753600,
    socket: 1709441753601,
    lookup: 1709441753601,
    connect: 1709441753648,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1709441753695,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 0,
      tcp: 47,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 95
    }
  }
}

**Comment by 13059580947** [comment]
window 报错如下，不知道什么报错
![1731152549363](https://github.com/user-attachments/assets/bda32a6a-30ca-4a5b-a092-43699993d93b)

**Comment by gaoxiaoduan** [comment]
[node更新了，移除了assert关键字](https://github.com/nodejs/node/pull/52104)

使用`with`替换`assert`即可 [import pkg from "./package.json" assert { type: "json" };](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/blob/6dc3d95b87d5e00cdc46f744c1c9def39032e96f/rollup.config.ts#L6)
例如：`import pkg from "./package.json" with { type: "json" };`
