### ISSUE TITLE
监听过程中捕获到错误

### ISSUE THREAD

**Issue by Doutianbao** [gaoxiaoduan/YoutubeToBilibiliHelp#3]
above

**Comment by Doutianbao** [comment]
![image](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/assets/25342342/e5e97604-5d7f-40be-815f-8cfb595b84f5)


arm64  debian11

**Comment by gaoxiaoduan** [comment]
upload_log.json文件没有配置正确，不能有注释的

**Comment by Doutianbao** [comment]
> upload_log.json文件没有配置正确，不能有注释的


没有注释~  还是不正确

**Comment by Doutianbao** [comment]
> upload_log.json文件没有配置正确，不能有注释的

![image](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/assets/25342342/b1c75a59-2e2c-4f52-a34f-cbda0f253b0b)
使用默认的upload_log.json文件，如上报错

**Comment by gaoxiaoduan** [comment]
这是配置文件正确了，但是代理（翻墙）没有配置上，你用的clash吗？

代理需要配置一下，不然没办法访问到油管
```ts
// src\constant\index.ts
// 代理->设置为"",则不走代理｜若直连，可能会被墙，建议给终端走代理，这里默认使用clash本地代理
export const PROXY = "http://127.0.0.1:7890";
```

**Comment by Doutianbao** [comment]
> 要配置一下，不然没办法访问到油管

韩国甲骨文

**Comment by Doutianbao** [comment]
> 这是配置文件正确了，但是代理（翻墙）没有配置上，你用的clash吗？
> 
> 代理需要配置一下，不然没办法访问到油管
> 
> ```ts
> // src\constant\index.ts
> // 代理->设置为"",则不走代理｜若直连，可能会被墙，建议给终端走代理，这里默认使用clash本地代理
> export const PROXY = "http://127.0.0.1:7890";
> ```

所以我应该注释掉这个代理~   对吧:)

**Comment by gaoxiaoduan** [comment]
不对，你的设备要可以翻墙，可以把PROXY的地址，更换成你自己的代理

**Comment by Doutianbao** [comment]
> 不对，你的设备要可以翻墙，可以把PROXY的地址，更换成你自己的代理

vps本来就是墙外，这里咋设置PROXY呢~ 
我注释了不行，代码里有寻找这个PROXY

**Comment by Doutianbao** [comment]
![image](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/assets/25342342/8f7702e3-1e0b-4049-a9c8-c16b0fd86e80)
我把需要proxy的地方都删除。  成功运行~
谢谢大佬的分享。

小白再问一个问题，上传后服务器的视频会删除吗？

**Comment by gaoxiaoduan** [comment]
本身就是墙外vps是ok的，两种方法，
第一种：把PROXY设置成空字符串，像下面这样，空字符会不走代理，进行直连
```ts
export const PROXY = "";
```

第二种，把代码里用到PROXY的地方删除，这样也会直连，可以全局搜索  "--proxy", `${PROXY}`,    替换成空字符
举例：
```ts
let commands = [`${videoURL}`, "--proxy", `${PROXY}`, "-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"

// 删除"--proxy", `${PROXY}`,  ->变成下面这样
let commands = [`${videoURL}`, "-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"


```

**Comment by gaoxiaoduan** [comment]
@Doutianbao 暂时还没有做自动删除视频的功能，需要手动上去清一下，二期会做这个功能

**Comment by Doutianbao** [comment]
> 

1.那是什么下载逻辑上传逻辑呢？  下载一个上传一个，不手动停止的话会一下下载？


2.linux默认没有微软雅黑字体，会疯狂报错
![image](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/assets/25342342/06aa4222-f5bb-4ce5-b798-a2d5f798cb4d)

**Comment by Doutianbao** [comment]
![image](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/assets/25342342/98a9d254-5923-4df1-bf25-fc4150f739a0)



3.linux版本不会指的是 linux  destop 吧 - -

**Comment by gaoxiaoduan** [comment]
逻辑：监听配置文件的视频是否有更新，如果发现更新就会去下载->加字幕->上传到平台->根据配置文件填写投稿信息，然后提交

没有字体的话，可以把`FontName=微软雅黑,`给删掉，这样就会用默认字体

**Comment by gaoxiaoduan** [comment]
linux版本不是 linux destop，这个是因为你在dev模式下启动的，dev模式下会打开桌面浏览器

**Comment by gaoxiaoduan** [comment]
可以把`headless: !isDev,`注释了，然后再运行`pnpm dev`

https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/blob/461964084c268cae8542068a0c3c04e4b5dcd565/src/utils/upload.ts#L18

**Comment by Doutianbao** [comment]
这或许就是大佬吧= =。问啥都能解答

期待二期新功能

Respect!

**Comment by Doutianbao** [comment]
bing翻译不敢恭维呀。
我发现哔哩哔哩平台自动生成的中英文字幕到还不错。
大佬可以试试

**Comment by it985** [comment]
你好，请问lz如何部署到vps

**Comment by Doutianbao** [comment]
> 可以把`headless: !isDev,`注释了，然后再运行`pnpm dev`
> 
> https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/blob/461964084c268cae8542068a0c3c04e4b5dcd565/src/utils/upload.ts#L18

注释了 还是没有成功。

**Comment by gaoxiaoduan** [comment]
> bing翻译不敢恭维呀。 我发现哔哩哔哩平台自动生成的中英文字幕到还不错。 大佬可以试试

必应用来翻译视频标题，B站的自动翻译，在B站打开视频字幕直接就可以看呀～

**Comment by gaoxiaoduan** [comment]
> > 可以把`headless: !isDev,`注释了，然后再运行`pnpm dev`
> > https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/blob/461964084c268cae8542068a0c3c04e4b5dcd565/src/utils/upload.ts#L18
> 
> 注释了 还是没有成功。

在dev模式下，注释`headless: !isDev`应该是可以的呀，像下面这样，请问现在成功了吗？
```ts

    log("启动浏览器...\n");
    const browser = await puppeteer.launch({
        // headless: !isDev, // 默认为true，无头模式
        args: ["--no-sandbox"],
        slowMo: 250,
        userDataDir: puppeteerUserDataDir,
        protocolTimeout: waitForSelectorTimeout
    });
```
