### ISSUE TITLE
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:

### ISSUE THREAD

**Issue by whooooo589** [gaoxiaoduan/YoutubeToBilibiliHelp#4]
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
SyntaxError: Unexpected token / in JSON at position 383
    at JSON.parse (<anonymous>)
    at getConfigFile (/root/YoutubeToBilibiliHelp/temp/utils/getConfigFile.js:17:25)
    at /root/YoutubeToBilibiliHelp/temp/index.js:46:66
    at Generator.next (<anonymous>)
    at /root/YoutubeToBilibiliHelp/temp/index.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/root/YoutubeToBilibiliHelp/temp/index.js:27:12)
    at main (/root/YoutubeToBilibiliHelp/temp/index.js:43:12)
    at Object.<anonymous> (/root/YoutubeToBilibiliHelp/temp/index.js:71:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)

**Comment by gaoxiaoduan** [comment]
报错提示：配置文件`upload_log.json`解析错误，请检查`upload_log.json`语法是否正确，注意标点符号 & json文件不能写注释

**Comment by whooooo589** [comment]
> 报错提示：配置文件`upload_log.json`解析错误，请检查`upload_log.json`语法是否正确，注意标点符号 & json文件不能写注释

好的 顺带一提，是填写uid还是账号名？

**Comment by whooooo589** [comment]
我的写法是
      "blibli_classification": [
      "xx",
      "xxx"
      ],
      "prefix_tags": [
      "xxx",
      "xxx",
      "xxx",
      "xxx"
      ],

**Comment by gaoxiaoduan** [comment]
可以参考`upload_log.template.json`文件里配置的写法，你上面说的写法是有问题的。

> 我的写法是 "blibli_classification": [ "xx", "xxx" ], "prefix_tags": [ "xxx", "xxx", "xxx", "xxx" ],

**Comment by whooooo589** [comment]
> 可以参考`upload_log.template.json`文件里配置的写法，你上面说的写法是有问题的。
> 
> > 我的写法是 "blibli_classification": [ "xx", "xxx" ], "prefix_tags": [ "xxx", "xxx", "xxx", "xxx" ],

好的 config里面的b站账号应该填写uid还是按注释来填？

**Comment by gaoxiaoduan** [comment]
不是uid，自己的账号哦，应该是手机号或者邮箱的形式

**Comment by whooooo589** [comment]
> 不是uid，自己的账号哦，应该是手机号或者邮箱的形式

好的 监听时间能更改吗

**Comment by gaoxiaoduan** [comment]
对`监听时间`这个概念，不太理解。
要监听的频道，更新后，就会自动执行从一系列操作，上传到B站平台上。
相对于到，要监听的频道没有更新的话，就会一直处于等待频道更新的状态。

**Comment by whooooo589** [comment]
> 对`监听时间`这个概念，不太理解。 要监听的频道，更新后，就会自动执行从一系列操作，上传到B站平台上。 相对于到，要监听的频道没有更新的话，就会一直处于等待频道更新的状态。

差不多就是更改请求youtube api的时间，因为日志里监听时间显示为600s，我感觉有点慢

**Comment by gaoxiaoduan** [comment]
这个可以修改的，修改[TASK_INTERVAL](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/blob/0e7bc4ff4b5bb168522a53a3ae641deca4680e23/src/constant/index.ts#L11C4-L11C4)常量就可以，代码里(1000 * 60 * 10)是指（(1秒 * 60 = 1分钟) * 10）是10分钟

**Comment by whooooo589** [comment]
> 这个可以修改的，修改[TASK_INTERVAL](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/blob/0e7bc4ff4b5bb168522a53a3ae641deca4680e23/src/constant/index.ts#L11C4-L11C4)常量就可以，代码里(1000 * 60 * 10)是指（(1秒 * 60 = 1分钟) * 10）是10分钟

修改了之后还是显示 600s 1000 * 60 * 1

**Comment by gaoxiaoduan** [comment]
修改之后需要重写build一下,再启动
```
pnpm build # build项目
pm2 start pm2.config.json # 启动项目
```

**Comment by whooooo589** [comment]
> 修改之后需要重写build一下,再启动
> 
> ```
> pnpm build # build项目
> pm2 start pm2.config.json # 启动项目
> ```

thx

**Comment by yhuhuhulwkd** [comment]
Google搜了下没头绪
