### ISSUE TITLE
centos环境下下载视频失败

### ISSUE THREAD

**Issue by whooooo589** [gaoxiaoduan/YoutubeToBilibiliHelp#5]
07-13 07:57:21: 视频下载错误
 Error: 
Error code: 1

Stderr:
ERROR: Postprocessing: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

07-13 07:57:21: 视频下载过程中出错： false
07-13 07:57:21: command: ffmpeg -i "/root/YoutubeToBilibiliHelp/videos/SharkBlox/2023_07_13__l4_usBWGs-U.webp" "/root/YoutubeToBilibiliHelp/videos/SharkBlox/2023_07_13__l4_usBWGs-U.png" -hide_banner
07-13 07:57:21: ffmpeg -i "/root/YoutubeToBilibiliHelp/videos/SharkBlox/2023_07_13__l4_usBWGs-U.mp4" -vf "subtitles=/root/YoutubeToBilibiliHelp/videos/SharkBlox/2023_07_13__l4_usBWGs-U.en.vtt:force_style='FontName=微软雅黑,PrimaryColour=&HFFFFFF&,BackColour=&H80000000&,BorderStyle=4,Outline=0,FontSize=9,MarginV=3',subtitles=/root/YoutubeToBilibiliHelp/videos/SharkBlox/2023_07_13__l4_usBWGs-U.zh-Hans.vtt:force_style='FontName=微软雅黑,PrimaryColour=&HFFFFFF&,BackColour=&H80000000&,BorderStyle=4,Outline=0,FontSize=14,MarginV=15'" -c:a copy "/root/YoutubeToBilibiliHelp/videos/SharkBlox/2023_07_13__l4_usBWGs-U.output.mp4" -hide_banner
07-13 07:57:21: command: ffmpeg -i "/root/YoutubeToBilibiliHelp/videos/SharkBlox/2023_07_13__l4_usBWGs-U.mp4" -vf "subtitles=/root/YoutubeToBilibiliHelp/videos/SharkBlox/2023_07_13__l4_usBWGs-U.en.vtt:force_style='FontName=微软雅黑,PrimaryColour=&HFFFFFF&,BackColour=&H80000000&,BorderStyle=4,Outline=0,FontSize=9,MarginV=3',subtitles=/root/YoutubeToBilibiliHelp/videos/SharkBlox/2023_07_13__l4_usBWGs-U.zh-Hans.vtt:force_style='FontName=微软雅黑,PrimaryColour=&HFFFFFF&,BackColour=&H80000000&,BorderStyle=4,Outline=0,FontSize=14,MarginV=15'" -c:a copy "/root/YoutubeToBilibiliHelp/videos/SharkBlox/2023_07_13__l4_usBWGs-U.output.mp4" -hide_banner
07-13 07:57:21: [1m[43m[30m
  Puppeteer old Headless deprecation warning:[0m[33m
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.[0m

07-13 07:57:21: main:捕获到错误-> Error: Failed to launch the browser process!
/root/.cache/puppeteer/chrome/linux-1108766/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://pptr.dev/troubleshooting

**Comment by gaoxiaoduan** [comment]
@yhuhuhulwkd pptr已更新到21版本，可重新安装项目进行测试，我在centos7环境下正常使用

**Comment by gaoxiaoduan** [comment]
@yhuhuhulwkd 需要删除项目下的`puppeteer`目录，然后重新编译运行

**Comment by whooooo589** [comment]
> @yhuhuhulwkd 需要删除项目下的`puppeteer`目录，然后重新编译运行

收到
