### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by whooooo589** [gaoxiaoduan/YoutubeToBilibiliHelp#6]
[logs.txt](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/files/12289069/logs.txt)

**Comment by gaoxiaoduan** [comment]
貌似是油管视频的格式错误导致的，重新跑一下还会报相同的错误吗？近期会出一个稳定版本。目前还有很多需要完善的地方

**Comment by whooooo589** [comment]
> 貌似是油管视频的格式错误导致的，重新跑一下还会报相同的错误吗？近期会出一个稳定版本。目前还有很多需要完善的地方

会

**Comment by whooooo589** [comment]
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:170
PM2        |       throw err;
PM2        |       ^
PM2        | 
PM2        | [Error: ENOENT: no such file or directory, open '/root/YoutubeToBilibiliHelp/logs/out-0.log'] {
PM2        |   errno: -2,
PM2        |   code: 'ENOENT',
PM2        |   syscall: 'open',
PM2        |   path: '/root/YoutubeToBilibiliHelp/logs/out-0.log'
PM2        | }
PM2        | 
PM2        | Node.js v18.17.0
PM2        | 2023-08-09T15:57:58: PM2 log: App name:ytToX id:0 disconnected
PM2        | 2023-08-09T15:57:58: PM2 log: App [ytToX:0] exited with code [1] via signal [SIGINT]
PM2        | 2023-08-09T15:57:58: PM2 log: Script /root/YoutubeToBilibiliHelp/temp/index.js had too many unstable restarts (16). Stopped. "errored"

**Comment by whooooo589** [comment]
最新的库覆盖后不会主动生成logs文件夹及相关logs文件，需自行创建，但之前的问题仍然存在

**Comment by gaoxiaoduan** [comment]
可以发一下`upload_log.json`文件吗？为了方便复现这个报错信息

**Comment by whooooo589** [comment]
> 可以发一下`upload_log.json`文件吗？为了方便复现这个报错信息

{
  "supported_target_platform": [
    "BZ"
  ],
  "uploads": [
    {
      "user": "google",
      "user_url": "https://www.youtube.com/@google/videos",
      "publish_prefix": "「机翻」",
      "blibli_classification": [
        0,
        0
      ],
      "prefix_tags": [
        "Youtube",
        "Google"
      ],
      "skip_down_subs": false,
      "skip_translation_title": false,
      "skip_upload_thumbnail": false,
      "submission_categories": false,
      "videos": []
    }
  ]
}

**Comment by gaoxiaoduan** [comment]
@yhuhuhulwkd 修改了一下代码，可以重新跑一下试试，`git pull`后，删除`puppeteer`文件夹，然后执行`build`命令打包，用`pm2 start pm2.config.json`运行

**Comment by whooooo589** [comment]
> @yhuhuhulwkd 修改了一下代码，可以重新跑一下试试，`git pull`后，删除`puppeteer`文件夹，然后执行`build`命令打包，用`pm2 start pm2.config.json`运行

You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/root/YoutubeToBilibiliHelp/temp/index.js' imported from /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:324:11)
    at moduleResolve (node:internal/modules/esm/resolve:943:10)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:524:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1188:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:429:21

**Comment by gaoxiaoduan** [comment]
我修改后build后的代码在dist目录下，这边报错信息显示temp下，`/root/YoutubeToBilibiliHelp/temp/index.js`，是不是你pm2的使用方法不对？

**Comment by whooooo589** [comment]
> 我修改后build后的代码在dist目录下，这边报错信息显示temp下，`/root/YoutubeToBilibiliHelp/temp/index.js`，是不是你pm2的使用方法不对？

合理来说应该是对的

**Comment by gaoxiaoduan** [comment]
> @yhuhuhulwkd 修改了一下代码，可以重新跑一下试试，`git pull`后，删除`puppeteer`文件夹，然后执行`build`命令打包，用`pm2 start pm2.config.json`运行

根据这个步骤执行，pnpm build后的代码出现在dist目录下才对，pm2的配置文件，也是以dist目录为[入口执行](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/blob/a548cad309ba7f0ed8aacb0839fe1605ddc97f1a/pm2.config.json#L3)的
或者配置文件留着，把项目删除，重新拉一份

**Comment by whooooo589** [comment]
> > @yhuhuhulwkd 修改了一下代码，可以重新跑一下试试，`git pull`后，删除`puppeteer`文件夹，然后执行`build`命令打包，用`pm2 start pm2.config.json`运行
> 
> 根据这个步骤执行，pnpm build后的代码出现在dist目录下才对，pm2的配置文件，也是以dist目录为[入口执行](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/blob/a548cad309ba7f0ed8aacb0839fe1605ddc97f1a/pm2.config.json#L3)的 或者配置文件留着，把项目删除，重新拉一份

依旧

**Comment by whooooo589** [comment]
已解决，原因为pm2缓存，运行后仍然报错

**Comment by whooooo589** [comment]
08-10 05:30:15: 项目启动～🚀
08-10 05:30:15: 当前环境为：正式环境
08-10 05:30:15: 开始监听任务
08-10 05:30:15: 开启一轮频道监测～
08-10 05:30:21: 捕获到错误：视频获取阶段  
08-10 05:30:21: 等待60s后开启新一轮监听
08-10 05:30:21: getPlaylistEnd错误
 Error: 
Error code: 1

Stderr:
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = DuzN_fS4AY60GhfZG ; player = https://www.youtube.com/s/player/4eae42b1/player_ias.vflset/en_US/base.js
Tejq14dVWtk: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2496, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2524, in _extract_n_function
    func_code = jsi.extract_function_code(funcname)
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 498, in extract_function_code
    code, _ = self._separate_at_paren(func_m.group('code'), '}')  # refine the match
  File "/usr/lib/python3/dist-packages/yt_dlp/jsinterp.py", line 117, in _separate_at_paren
    raise ExtractorError(f'No terminating paren {delim} in {expr}')
yt_dlp.utils.ExtractorError: No terminating paren } in {var b=a.split(""),c=[function(d){throw d;},
-495432057,1419553194,function(){for(var d=64,e=[];++d-e.length-32;)switch(d){case 58:d=96;continue;case 91:d=44;break;case 65:d=47;continue;case 46:d=153;case 123:d-=58;default:e.push(String.fromCharCode(d))}return e},
function(){for(var d=64,e=[];++d-e.length-32;){switch(d){case 58:d-=14;case 91:case 92:case 93:continue;case 123:d=47;case 94:case 95:case 96:continue;case 46:d=95}e.push(String.fromCharCode(d))}return e},
function(d){throw d;},
function(d,e){d=(d%e.length+e.length)%e.length;e.splice(-d).reverse().forEach(function(f){e.unshift(f)})},
function(){for(var d=64,e=[];++d-e.length-32;){switch(d){case 91:d=44;continue;case 123:d=65;break;case 65:d-=18;continue;case 58:d=96;continue;case 46:d=95}e.push(String.fromCharCode(d))}return e},
-1644147250,-239099945,392753800,1603749834,/("(,),\/()(})(;))[)]/,1915247590,119161037,1482014444,function(d,e,f,h,l,m,n,p){return d(m,n,p)},
-1533358013,b,function(d,e,f,h,l,m,n,p){return e(f,h,l,m,n,p)},
function(d,e,f,h,l,m,n,p,q,t,u){return n(q,t,u)},
-704894437,-548263437,1573387471,831426297,615724542,1275261611,1352959305,-319861807,1701296985,-1348343710,1587194622,function(d,e,f,h,l,m,n,p,q,t,u){return d(f,h,l,m,n,p,q,t,u)},
-610789273,2016591694,function(d,e){e=(e%d.length+d.length)%d.length;d.splice(e,1)},
-979850935,-1095826516,2011692205,-566314311,1797970233,-1357604016,"Xmh5Y6F",-610789273,b,113021354,function(d,e){if(0!=d.length){e=(e%d.length+d.length)%d.length;var f=d[0];d[0]=d[e];d[e]=f}},
-1725383439,1419553194,-94525618,1915247590,1117257866,b,-708492721,-1136299216,-1898875059,-1390132541,-1446684735,null,function(d,e,f,h,l){return e(f,h,l)},
function(d,e,f,h,l,m){return e(h,l,m)},
function(d,e,f,h,l,m,n,p,q){return f(h,l,m,n,p,q)},
376840177,function(d,e){d.splice(d.length,0,e)},
1117257866,function(d){for(var e=d.length;e;)d.push(d.splice(--e,1)[0])},
2047922294,-1390794314,null,-2054916259,1622477878,612618873,function(d,e){0!=e.length&&(d=(d%e.length+e.length)%e.length,e.splice(0,1,e.splice(d,1,e[0])[0]))},
-776696356,",,})){,",function(d){d.reverse()},
331215784,-698752151,901260571,function(d,e,f){var h=e.length;f.forEach(function(l,m,n){this.push(n[m]=e[(e.indexOf(l)-e.indexOf(this[m])+m+h--)%e.length])},d.split(""))},
function(d,e){for(d=(d%e.length+e.length)%e.length;d--;)e.unshift(e.pop())},
function(d,e,f,h,l){return e(f,h,l)},
"Xmh5Y6F",-1354621752,function(d,e,f,h,l,m,n){return d(l,m,n)},
null,-2000727756,1003576615,"splice",'[/,"u',-401622058];c[58]=c;c[68]=c;c[85]=c;try{try{-2!==c[67]&&(3===c[Math.pow(1,3)+208+-138]&&(((((0,c[new Date("1969-12-31T16:00:35.000-08:00")/1E3])(c[18],c[30]),c[59])((0,c[79])(c[42],(0,c[7])(),c[18]),c[79],c[-194*Math.pow(3,3)+5280],(0,c[3])(),c[52]),(0,c[79])(c[82],(0,c[7])(),c[52]),c[35])(c[58],c[28]),c[35])(c[new Date("1969-12-31T19:15:52.000-04:45")/1E3],c[86]),1)||(0,c[19])((0,c[19])((0,c[59])((0,c[6])(c[56],c[58]),c[86],c[15]),c[79],(0,c[63])(c[40],
c[25]),c[6],c[75],c[72]),c[new Date("1970-01-01T04:30:10.000+04:30")/1E3],(0,c[6])(c[75],c[2]),c[81],c[78],(0,c[65])(),c[51])),((0,c[new Date("1970-01-01T11:16:09.000+11:15")/1E3])(c[235*Math.pow(8,5)+new Date("1969-10-04T02:59:31.000+06:00")/1E3]),c[34])(c[17],c[5])}catch(d){-7>c[77]?(0,c[49])((0,c[79])(((0,c[80])(c[44],c[1]),c[88])(c[48],c[51]),c[63],c[33],c[75]),(0,c[28])(c[32],c[66]),(0,c[Math.pow(6,2)+184%(new Date("1969-12-31T13:06:56.000-11:00")/1E3)+-169])((0,c[36])(c[30],c[58]),c[33],c[42]),
(0,c[56])(c[25],c[69]),(0,c[64])(c[67],c[50]),(0,c[14])((0,c[38])(((0,c[20])(c[249715-104*Math.pow(7,4)]),c[29])(c[70],c[23]),c[83],c[7],c[72]),c[32],c[11]),c[20],(0,c[54])(c[71],c[42]),c[78]):(((0,c[66])(c[27],(0,c[53])(((0,c[69])(c[78],c[377%Math.pow(1,4)- -82]),c[24])((0,c[23])(c[65],c[28]),c[22],c[12],(0,c[37])(),c[78]),c[24],(0,c[69])(c[92],c[48]),c[18],c[92]),c[80],(0,c[239+Math.pow(5,2)+-195])(c[90],c[new Date("1970-01-01T07:30:14.000+07:30")/1E3]),((0,c[6])(c[28]),(0,c[69])(c[90],c[45]),c[69])(c[86],
c[73]),(0,c[69])(c[78],c[new Date("1970-01-01T07:16:12.000+07:15")/1E3]),c[350%Math.pow(5,1)- -78],c[88]),c[18])(c[86]),c[0])((0,c[69])(c[86],c[8]),c[22],c[31],(0,c[37])(),c[86])}try{(-1===c[63]||((0,c[1])(((0,c[80])(c[92],c[81]),((0,c[15])(c[13],c[28]),((0,c[23])(c[83],c[9]),c[62])(c[54],c[75]),c[62])(c[91],c[32])),c[87],(0,c[51])(c[75],c[87]),c[14],c[32]),NaN))&&(0,c[49])(((((0,c[53])(c[56]),c[65])(c[46]),c[69])(c[59],(0,c[84])(),c[44]),c[70])(c[25],c[32]),(0,c[62])(c[158-Math.pow(7,3)- -203],c[56]),
c[38],(0,c[69])(c[78],(0,c[88])(),c[40]),c[34],c[32],c[50]),(-5>c[66]||((((0,c[4])(c[62],(0,c[70])(c[33],c[32]),((0,c[70])(c[5],c[56]),c[35])(c[89],c[19]),(0,c[-54777+214*Math.pow(4,4)])(c[48],c[62]),(0,c[90])(c[Math.pow(3,3)+18+-32],c[18]),c[53],c[19]),c[21])(((0,c[66])(c[2],c[5]),c[66])(c[63],c[13]),c[90],(0,c[11])((0,c[42])(c[32],(0,c[61])(),c[13]),c[43],c[1],c[5]),c[13],c[70]),c[35])(c[30],c[5]),0))&&((((((((0,c[44])((0,c[43])(c[55],c[13]),c[42],c[3],(0,c[57])(),c[5]),c[90])(c[5],c[50]),c[43])(c[14],
c[48]),c[26])(c[17]),c[42])(c[51],(0,c[57])(),c[13]),(0,c[7])(c[29],c[40]),c[21])((0,c[42])(c[3],(0,c[57])(),c[5]),c[42],(0,c[35])(c[36],c[13]),c[Math.pow(1,3)%225- -50],(0,c[57])(),c[5]),c[42])(c[51],(0,c[58])(),c[5]),c[35])(c[82],c[-4773-Math.pow(5,2)- -4827])}catch(d){(0,c[44])((0,c[90])(c[5],c[8-Math.pow(1,4)+9]),c[42],c[new Date("1970-01-01T06:15:51.000+06:15")/1E3],(0,c[57])(),c[5])}}catch(d){return"enhanced_except_-JgBh-f-_w8_"+a}return b.join("")}; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
 (caused by ExtractorError('No terminating paren } in {var b=a.split(""),c=[function(d){throw d;},\n-495432057,1419553194,function(){for(var d=64,e=[];++d-e.length-32;)switch(d){case 58:d=96;continue;case 91:d=44;break;case 65:d=47;continue;case 46:d=153;case 123:d-=58;default:e.push(String.fromCharCode(d))}return e},\nfunction(){for(var d=64,e=[];++d-e.length-32;){switch(d){case 58:d-=14;case 91:case 92:case 93:continue;case 123:d=47;case 94:case 95:case 96:continue;case 46:d=95}e.push(String.fromCharCode(d))}return e},\nfunction(d){throw d;},\nfunction(d,e){d=(d%e.length+e.length)%e.length;e.splice(-d).reverse().forEach(function(f){e.unshift(f)})},\nfunction(){for(var d=64,e=[];++d-e.length-32;){switch(d){case 91:d=44;continue;case 123:d=65;break;case 65:d-=18;continue;case 58:d=96;continue;case 46:d=95}e.push(String.fromCharCode(d))}return e},\n-1644147250,-239099945,392753800,1603749834,/("(,),\\/()(})(;))[)]/,1915247590,119161037,1482014444,function(d,e,f,h,l,m,n,p){return d(m,n,p)},\n-1533358013,b,function(d,e,f,h,l,m,n,p){return e(f,h,l,m,n,p)},\nfunction(d,e,f,h,l,m,n,p,q,t,u){return n(q,t,u)},\n-704894437,-548263437,1573387471,831426297,615724542,1275261611,1352959305,-319861807,1701296985,-1348343710,1587194622,function(d,e,f,h,l,m,n,p,q,t,u){return d(f,h,l,m,n,p,q,t,u)},\n-610789273,2016591694,function(d,e){e=(e%d.length+d.length)%d.length;d.splice(e,1)},\n-979850935,-1095826516,2011692205,-566314311,1797970233,-1357604016,"Xmh5Y6F",-610789273,b,113021354,function(d,e){if(0!=d.length){e=(e%d.length+d.length)%d.length;var f=d[0];d[0]=d[e];d[e]=f}},\n-1725383439,1419553194,-94525618,1915247590,1117257866,b,-708492721,-1136299216,-1898875059,-1390132541,-1446684735,null,function(d,e,f,h,l){return e(f,h,l)},\nfunction(d,e,f,h,l,m){return e(h,l,m)},\nfunction(d,e,f,h,l,m,n,p,q){return f(h,l,m,n,p,q)},\n376840177,function(d,e){d.splice(d.length,0,e)},\n1117257866,function(d){for(var e=d.length;e;)d.push(d.splice(--e,1)[0])},\n2047922294,-1390794314,null,-2054916259,1622477878,612618873,function(d,e){0!=e.length&&(d=(d%e.length+e.length)%e.length,e.splice(0,1,e.splice(d,1,e[0])[0]))},\n-776696356,",,})){,",function(d){d.reverse()},\n331215784,-698752151,901260571,function(d,e,f){var h=e.length;f.forEach(function(l,m,n){this.push(n[m]=e[(e.indexOf(l)-e.indexOf(this[m])+m+h--)%e.length])},d.split(""))},\nfunction(d,e){for(d=(d%e.length+e.length)%e.length;d--;)e.unshift(e.pop())},\nfunction(d,e,f,h,l){return e(f,h,l)},\n"Xmh5Y6F",-1354621752,function(d,e,f,h,l,m,n){return d(l,m,n)},\nnull,-2000727756,1003576615,"splice",\'[/,"u\',-401622058];c[58]=c;c[68]=c;c[85]=c;try{try{-2!==c[67]&&(3===c[Math.pow(1,3)+208+-138]&&(((((0,c[new Date("1969-12-31T16:00:35.000-08:00")/1E3])(c[18],c[30]),c[59])((0,c[79])(c[42],(0,c[7])(),c[18]),c[79],c[-194*Math.pow(3,3)+5280],(0,c[3])(),c[52]),(0,c[79])(c[82],(0,c[7])(),c[52]),c[35])(c[58],c[28]),c[35])(c[new Date("1969-12-31T19:15:52.000-04:45")/1E3],c[86]),1)||(0,c[19])((0,c[19])((0,c[59])((0,c[6])(c[56],c[58]),c[86],c[15]),c[79],(0,c[63])(c[40],\nc[25]),c[6],c[75],c[72]),c[new Date("1970-01-01T04:30:10.000+04:30")/1E3],(0,c[6])(c[75],c[2]),c[81],c[78],(0,c[65])(),c[51])),((0,c[new Date("1970-01-01T11:16:09.000+11:15")/1E3])(c[235*Math.pow(8,5)+new Date("1969-10-04T02:59:31.000+06:00")/1E3]),c[34])(c[17],c[5])}catch(d){-7>c[77]?(0,c[49])((0,c[79])(((0,c[80])(c[44],c[1]),c[88])(c[48],c[51]),c[63],c[33],c[75]),(0,c[28])(c[32],c[66]),(0,c[Math.pow(6,2)+184%(new Date("1969-12-31T13:06:56.000-11:00")/1E3)+-169])((0,c[36])(c[30],c[58]),c[33],c[42]),\n(0,c[56])(c[25],c[69]),(0,c[64])(c[67],c[50]),(0,c[14])((0,c[38])(((0,c[20])(c[249715-104*Math.pow(7,4)]),c[29])(c[70],c[23]),c[83],c[7],c[72]),c[32],c[11]),c[20],(0,c[54])(c[71],c[42]),c[78]):(((0,c[66])(c[27],(0,c[53])(((0,c[69])(c[78],c[377%Math.pow(1,4)- -82]),c[24])((0,c[23])(c[65],c[28]),c[22],c[12],(0,c[37])(),c[78]),c[24],(0,c[69])(c[92],c[48]),c[18],c[92]),c[80],(0,c[239+Math.pow(5,2)+-195])(c[90],c[new Date("1970-01-01T07:30:14.000+07:30")/1E3]),((0,c[6])(c[28]),(0,c[69])(c[90],c[45]),c[69])(c[86],\nc[73]),(0,c[69])(c[78],c[new Date("1970-01-01T07:16:12.000+07:15")/1E3]),c[350%Math.pow(5,1)- -78],c[88]),c[18])(c[86]),c[0])((0,c[69])(c[86],c[8]),c[22],c[31],(0,c[37])(),c[86])}try{(-1===c[63]||((0,c[1])(((0,c[80])(c[92],c[81]),((0,c[15])(c[13],c[28]),((0,c[23])(c[83],c[9]),c[62])(c[54],c[75]),c[62])(c[91],c[32])),c[87],(0,c[51])(c[75],c[87]),c[14],c[32]),NaN))&&(0,c[49])(((((0,c[53])(c[56]),c[65])(c[46]),c[69])(c[59],(0,c[84])(),c[44]),c[70])(c[25],c[32]),(0,c[62])(c[158-Math.pow(7,3)- -203],c[56]),\nc[38],(0,c[69])(c[78],(0,c[88])(),c[40]),c[34],c[32],c[50]),(-5>c[66]||((((0,c[4])(c[62],(0,c[70])(c[33],c[32]),((0,c[70])(c[5],c[56]),c[35])(c[89],c[19]),(0,c[-54777+214*Math.pow(4,4)])(c[48],c[62]),(0,c[90])(c[Math.pow(3,3)+18+-32],c[18]),c[53],c[19]),c[21])(((0,c[66])(c[2],c[5]),c[66])(c[63],c[13]),c[90],(0,c[11])((0,c[42])(c[32],(0,c[61])(),c[13]),c[43],c[1],c[5]),c[13],c[70]),c[35])(c[30],c[5]),0))&&((((((((0,c[44])((0,c[43])(c[55],c[13]),c[42],c[3],(0,c[57])(),c[5]),c[90])(c[5],c[50]),c[43])(c[14],\nc[48]),c[26])(c[17]),c[42])(c[51],(0,c[57])(),c[13]),(0,c[7])(c[29],c[40]),c[21])((0,c[42])(c[3],(0,c[57])(),c[5]),c[42],(0,c[35])(c[36],c[13]),c[Math.pow(1,3)%225- -50],(0,c[57])(),c[5]),c[42])(c[51],(0,c[58])(),c[5]),c[35])(c[82],c[-4773-Math.pow(5,2)- -4827])}catch(d){(0,c[44])((0,c[90])(c[5],c[8-Math.pow(1,4)+9]),c[42],c[new Date("1970-01-01T06:15:51.000+06:15")/1E3],(0,c[57])(),c[5])}}catch(d){return"enhanced_except_-JgBh-f-_w8_"+a}return b.join("")}; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

**Comment by gaoxiaoduan** [comment]
这是服务环境的问题导致的，跟刚才的报错不一样。
环境问题导致的，后面会用docker解决

**Comment by whooooo589** [comment]
> 

ubuntu20.04，甲骨云amd，apt源拉的yt-dlp

**Comment by gaoxiaoduan** [comment]
我没有这个环境去复现错误，还是直接使用docker磨平环境差异吧

**Comment by whooooo589** [comment]
> yt-dlp -U

2022.3那版的有点老

**Comment by whooooo589** [comment]
升级了下可以了

**Comment by gaoxiaoduan** [comment]
好的～

**Comment by whooooo589** [comment]
另外再问个问题佬，这个识图平台有啥用

**Comment by gaoxiaoduan** [comment]
如果同一天里发布特别频繁的话，平台那边会跳验证码，这个识图平台是为了过二次验证用的

**Comment by whooooo589** [comment]
> 如果同一天里发布特别频繁的话，平台那边会跳验证码，这个识图平台是为了过二次验证用的

应该没有哪一个高产那么多吧

**Comment by whooooo589** [comment]
现在就是有个问题，加字幕的时候卡住了

**Comment by gaoxiaoduan** [comment]
项目支持多频道共同检测的，可能同一天内会有不同的频道更新视频

**Comment by gaoxiaoduan** [comment]
加字幕这个操作，比较占cpu，会比较慢，耐心等待就行

**Comment by whooooo589** [comment]
youtube用的是谷歌自家的验证码吧，好像有项目可以不用平台识别，万一这个平台哪一天就倒了那不好说

**Comment by gaoxiaoduan** [comment]
如果一个视频10分钟，在单核cup的环境下，可能会需要20-30分钟的样子才能处理完字幕

**Comment by gaoxiaoduan** [comment]
倒了我会及时更换处理的

**Comment by whooooo589** [comment]
> 如果一个视频10分钟，在单核cup的环境下，可能会需要20-30分钟的样子才能处理完字幕

为啥那么久，我的AMD单核折腾不起，甲骨可能会识别成挖矿

**Comment by gaoxiaoduan** [comment]
这个操作本身就重，可以在配置文件中跳过加字幕的过程，文档中有写配置项哈

**Comment by whooooo589** [comment]
> 这个操作本身就重，可以在配置文件中跳过加字幕的过程，文档中有写配置项哈

b站上传字幕不是在最下面有个框吗

**Comment by whooooo589** [comment]
我觉得可以用Python模拟点击

**Comment by gaoxiaoduan** [comment]
> 我觉得可以用Python模拟点击

欢迎PR

**Comment by whooooo589** [comment]
> > 我觉得可以用Python模拟点击
> 
> 欢迎PR

我写的是屎山

**Comment by whooooo589** [comment]
没啥事了我就close了佬
