### ISSUE TITLE
docker 报错 无法打开浏览器

### ISSUE THREAD

**Issue by whooooo589** [gaoxiaoduan/YoutubeToBilibiliHelp#8]
Puppeteer old Headless deprecation warning:
    In the near future `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
09-02 03:03:01: main:捕获到错误-> Error: Failed to launch the browser process! spawn /usr/bin/chromium ENOENT
TROUBLESHOOTING: https://pptr.dev/troubleshooting

src/browser/index.ts 已将 headless 注释并添加 chromium 路径

**Comment by gaoxiaoduan** [comment]
@yhuhuhulwkd  由`/usr/bin/chromium`看出，是由于镜像缺少chromium导致此问题，已在v1.0.1版本修复

**Comment by whooooo589** [comment]
> @yhuhuhulwkd 由`/usr/bin/chromium`看出，是由于镜像缺少chromium导致此问题，已在v1.0.1版本修复

拉dev分支吗佬

**Comment by gaoxiaoduan** [comment]
main分支

**Comment by whooooo589** [comment]
> main分支

问题依旧
09-02 08:00:38: 启动浏览器
09-02 08:00:38: 
  Puppeteer old Headless deprecation warning:
    In the near future `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
09-02 08:00:38: main:捕获到错误-> Error: Failed to launch the browser process! spawn /usr/bin/chromium ENOENT
TROUBLESHOOTING: https://pptr.dev/troubleshooting
09-02 08:00:38: main:捕获到错误->60s后重新开启监听

**Comment by gaoxiaoduan** [comment]
docker 镜像需要重新build
`docker build -t youtube_to_bilibili_help .`
删除之前的容器，docker rm youtube ，最后再根据最新的镜像重新跑容器
`docker run -d --name youtube --net=host -v <本机upload.config.json文件>:/usr/app/upload.config.json youtube_to_bilibili_help`

**Comment by whooooo589** [comment]
> 

09-02 08:06:34: 视频下载错误
 Error: 
Error code: 1
Stderr:
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

**Comment by gaoxiaoduan** [comment]
这是网络环境问题

**Comment by whooooo589** [comment]
> 这是网络环境问题

网络正常

**Comment by whooooo589** [comment]
![image](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/assets/130195579/10d0d421-e244-4b02-97dc-4780eb38794e)

**Comment by gaoxiaoduan** [comment]
国外的vpn的话把这个设置为空字符串，文档有写[https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/blob/db1c02db10e74dd33bddd340cf9cf337dccefab2/src/constant/index.ts#L5](url)

**Comment by whooooo589** [comment]
> 

是空的

**Comment by whooooo589** [comment]
![image](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/assets/130195579/904851f1-a2a0-461b-8282-2ef6b0095c9e)

**Comment by whooooo589** [comment]
字幕能下载视频不能

**Comment by gaoxiaoduan** [comment]
> 09-02 08:06:34: 视频下载错误 Error: Error code: 1 Stderr: [download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries ERROR: fragment 1 not found, unable to continue

` HTTP Error 403: Forbidden`是因为你请求的太频繁了，ip被YouTube那边禁掉了，等一会再试就好了

**Comment by whooooo589** [comment]
> > 09-02 08:06:34: 视频下载错误 Error: Error code: 1 Stderr: [download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries ERROR: fragment 1 not found, unable to continue
> 
> ` HTTP Error 403: Forbidden`是因为你请求的太频繁了，ip被YouTube那边禁掉了，等一会再试就好了

今天试了一样

**Comment by gaoxiaoduan** [comment]
换个ip试试，我经常遇到这个403，就是被限制了
或者可以先完全停用一两天，不要后台运行，然后再尝试一下
