### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by whooooo589** [gaoxiaoduan/YoutubeToBilibiliHelp#9]
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
SyntaxError: Unexpected token s in JSON at position 382
    at JSON.parse (<anonymous>)
    at getConfigFile (file:///usr/app/dist/utils/files.js:23:25)
    at main (file:///usr/app/dist/index.js:14:20)
    at file:///usr/app/dist/index.js:36:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15)

**Comment by whooooo589** [comment]
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
SyntaxError: Unexpected token s in JSON at position 348
    at JSON.parse (<anonymous>)
    at getConfigFile (file:///usr/app/dist/utils/files.js:23:25)
    at main (file:///usr/app/dist/index.js:14:20)
    at file:///usr/app/dist/index.js:36:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15)

**Comment by whooooo589** [comment]
01-01 03:00:47: getPlaylistEnd错误
 Error: 
Error code: 1
Stderr:
WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (1/3)...
WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (2/3)...
WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (3/3)...
WARNING: [youtube:tab] Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'))). Giving up after 3 retries
WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (1/3)...
WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (2/3)...
WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (3/3)...
ERROR: [youtube:tab] @sharkblox: Unable to download API page: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused')))

**Comment by whooooo589** [comment]
Error: 
Error code: 1
Stderr:
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

**Comment by gaoxiaoduan** [comment]
> You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection: SyntaxError: Unexpected token s in JSON at position 382 at JSON.parse () at getConfigFile (file:///usr/app/dist/utils/files.js:23:25) at main (file:///usr/app/dist/index.js:14:20) at file:///usr/app/dist/index.js:36:1 at ModuleJob.run (node:internal/modules/esm/module_job:195:25) at async ModuleLoader.import (node:internal/modules/esm/loader:336:24) at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15)

这json parse报错，检查一下`upload.config.json`文件内容，是否符合json格式要求

**Comment by gaoxiaoduan** [comment]
> 01-01 03:00:47: getPlaylistEnd错误 Error: Error code: 1 Stderr: WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (1/3)... WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (2/3)... WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (3/3)... WARNING: [youtube:tab] Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'))). Giving up after 3 retries WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (1/3)... WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (2/3)... WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (3/3)... ERROR: [youtube:tab] @SharkBlox: Unable to download API page: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused')))



> Error: Error code: 1 Stderr: [download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries ERROR: fragment 1 not found, unable to continue

这两个是网络问题，或者请求太频繁了，被服务器限制了

**Comment by whooooo589** [comment]
> > You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection: SyntaxError: Unexpected token s in JSON at position 382 at JSON.parse () at getConfigFile (file:///usr/app/dist/utils/files.js:23:25) at main (file:///usr/app/dist/index.js:14:20) at file:///usr/app/dist/index.js:36:1 at ModuleJob.run (node:internal/modules/esm/module_job:195:25) at async ModuleLoader.import (node:internal/modules/esm/loader:336:24) at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15)
> 
> 这json parse报错，检查一下`upload.config.json`文件内容，是否符合json格式要求

文档里的json格式有问题，建议改一下

**Comment by whooooo589** [comment]
> > 01-01 03:00:47: getPlaylistEnd错误 Error: Error code: 1 Stderr: WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (1/3)... WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (2/3)... WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (3/3)... WARNING: [youtube:tab] Unable to download webpage: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused'))). Giving up after 3 retries WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (1/3)... WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (2/3)... WARNING: [youtube:tab] <urlopen error [Errno 111] Connection refused>. Retrying (3/3)... ERROR: [youtube:tab] @SharkBlox: Unable to download API page: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused')))
> 
> > Error: Error code: 1 Stderr: [download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries ERROR: fragment 1 not found, unable to continue
> 
> 这两个是网络问题，或者请求太频繁了，被服务器限制了

我挂了全局，但是速度就很慢

**Comment by gaoxiaoduan** [comment]
> > > You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection: SyntaxError: Unexpected token s in JSON at position 382 at JSON.parse () at getConfigFile (file:///usr/app/dist/utils/files.js:23:25) at main (file:///usr/app/dist/index.js:14:20) at file:///usr/app/dist/index.js:36:1 at ModuleJob.run (node:internal/modules/esm/module_job:195:25) at async ModuleLoader.import (node:internal/modules/esm/loader:336:24) at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15)
> > 
> > 
> > 这json parse报错，检查一下`upload.config.json`文件内容，是否符合json格式要求
> 
> 文档里的json格式有问题，建议改一下

`upload.config.template.json`文件里的json格式没问题，文档中的`upload.config.json`为了方便理解加了备注，不可以拿来直接用，可以使用`upload.config.template.json`这个模版json

**Comment by whooooo589** [comment]
> > > > You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection: SyntaxError: Unexpected token s in JSON at position 382 at JSON.parse () at getConfigFile (file:///usr/app/dist/utils/files.js:23:25) at main (file:///usr/app/dist/index.js:14:20) at file:///usr/app/dist/index.js:36:1 at ModuleJob.run (node:internal/modules/esm/module_job:195:25) at async ModuleLoader.import (node:internal/modules/esm/loader:336:24) at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15)
> > > 
> > > 
> > > 这json parse报错，检查一下`upload.config.json`文件内容，是否符合json格式要求
> > 
> > 
> > 文档里的json格式有问题，建议改一下
> 
> `upload.config.template.json`文件里的json格式没问题，文档中的`upload.config.json`为了方便理解加了备注，不可以拿来直接用，可以使用`upload.config.template.json`这个模版json

下载慢的情况怎么解决呢

**Comment by gaoxiaoduan** [comment]
想办法给网络提提速。比如使用hysteria协议等等

**Comment by whooooo589** [comment]
> 想办法给网络提提速。比如使用hysteria协议等等

我连的是亚太，欧美网络一样403，可能只能家宽，本地服务器10G，连节点可以拉满

**Comment by gaoxiaoduan** [comment]
HTTP Error 403: Forbidden，是服务器拒绝响应了

**Comment by gaoxiaoduan** [comment]
大概率是请求太频繁了

**Comment by whooooo589** [comment]
> 大概率是请求太频繁了

6

**Comment by whooooo589** [comment]
不会啊

**Comment by gaoxiaoduan** [comment]
我后面更新一个自定义请求频率的配置项上去，服务器403我也没办法的

**Comment by gaoxiaoduan** [comment]
一般隔天就好了，要么就是搞一个节点池应对403的情况，感觉没太大的必要性

**Comment by whooooo589** [comment]
> 一般隔天就好了，要么就是搞一个节点池应对403的情况，感觉没太大的必要性

我这是隔了一个月再来测的

**Comment by gaoxiaoduan** [comment]
> 我后面更新一个自定义请求频率的配置项上去，服务器403我也没办法的

已更新[自定义频率的配置文档](https://github.com/gaoxiaoduan/YoutubeToBilibiliHelp/pull/10)上去
